Magazine/Areas/Admin/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Magazine.Models;
using Magazine.Areas.Admin.ViewModels;
using System.Net;
using System.Data.Entity;

namespace Magazine.Areas.Admin.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly MagazineDbContext db = new MagazineDbContext();
        // Hiển thị danh sách bài viết
        public ActionResult Index()
        {
            var articles = db.Articles.Include("Category").OrderByDescending(a => a.ArticleID).ToList();

            return View(articles);
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            ViewBag.ListCategory = db.Categories.ToList();
            return View();
        }

        // POST: Article/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Article article)
        {
            if (ModelState.IsValid)
            {
                // set data
                article.ArticleImage = article.Link;
                article.PostTime = DateTime.Now;
                article.UserID = 1;

                // store article
                db.Articles.Add(article);
                db.SaveChanges();

                
                return RedirectToAction("Index");
            }

            ViewBag.ListCategory = db.Categories.ToList();
            return View();
        }

        // GET: Article/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Article article = db.Articles.Find(id);
            if (article == null)
                return HttpNotFound();

            ViewBag.CategoryID = article.CategoryID;
            ViewBag.ListCategory = db.Categories.ToList();
            return View(article);
        }

        // POST: Article/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Article article)
        {
            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.ListCategory = db.Categories.ToList();
            return View();
        }

        // GET: User/Delete/${id}
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Article article = db.Articles.Find(id);
            if (article == null)
                return HttpNotFound();

            return View(article);
        }

        // POST: User/Delete/${id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Phê duyệt bài viết
        [HttpPost]
        public ActionResult Approve(int id)
        {
            var article = db.Articles.Find(id);
            if (article != null)
            {
                article.ApprovalStatus = "Đã Duyệt";
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // Từ chối bài viết
        [HttpPost]
        public ActionResult Reject(int id, string feedback)
        {
            var article = db.Articles.Find(id);
            if (article != null)
            {
                article.ApprovalStatus = "Từ chối";
                article.Feedback = feedback;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // Yêu cầu chỉnh sửa bài viết
        [HttpPost]
        public ActionResult RequestEdit(int id, string feedback)
        {
            var article = db.Articles.Find(id);
            if (article != null)
            {
                article.ApprovalStatus = "Yêu cầu chỉnh sửa";
                article.Feedback = feedback;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Magazine/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Magazine.Areas.Admin.Controllers
{
    [Authorize]
    public class HomeAdminController : Controller
    {
        // GET: Admin/HomeAdmin
        public ActionResult Index()
        {
            return View();
        }
    }
}

Magazine/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity;
using Magazine.Models;
using System.Security.Cryptography;
using System.Text;

namespace Magazine.Areas.Admin.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private MagazineDbContext db = new MagazineDbContext();
        // GET: User/Index
        public ActionResult Index()
        {
            var users = db.Users.ToList();
            return View(users);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName");
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleID,Username,PasswordHash,Email,Fullname,Avatar")] User user)
        {
            if (ModelState.IsValid)
            {
                // set role
                user.RoleID = 3;

                // hash password
                user.PasswordHash = HashPassword(user.PasswordHash);

                // store user
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName", user.RoleID);
            return View(user);
        }

        private string HashPassword(string password)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                return Convert.ToBase64String(bytes);
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            User user = db.Users.Find(id);
            if (user == null)
                return HttpNotFound();

            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName", user.RoleID);
            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,RoleID,Username,PasswordHash,Email,Fullname,Avatar")] User user)
        {
            if (ModelState.IsValid)
            {
                // set role
                user.RoleID = 3;

                // hash password
                user.PasswordHash = HashPassword(user.PasswordHash);

                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoleID = new SelectList(db.Roles, "RoleID", "RoleName", user.RoleID);
            return View(user);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            User user = db.Users.Find(id);
            if (user == null)
                return HttpNotFound();

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Magazine/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@{
    ViewBag.Title = "Trang quản trị";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Areas/Admin/Content/css/Admin.css" />
</head>
<body>
    <div class="container-fluid">
        <!-- Sidebar -->
        <div class="row">
            <div class="col-md-2">
                @RenderPage("~/Areas/Admin/Views/Shared/_Sidebar.cshtml")
            </div>
            <!-- Main Content -->
            <div class="col-md-10">
                @RenderPage("~/Areas/Admin/Views/Shared/_Navbar.cshtml")
                <main role="main" class="pt-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>

Magazine/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="@Url.Action("Index", "Home",new { area = "" })"> </a>
    <ul class="navbar-nav ms-auto">
        <li class="nav-item">
            <a class="nav-link" href="#" style="margin-right: 15px;">Xin chào <strong><em>Admin</em></strong></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Logout", "Account")">Đăng xuất</a>
        </li>
    </ul>
</nav>

Magazine/Areas/Admin/Views/Shared/_Sidebar.cshtml
<div class="sidebar">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "HomeAdmin")">Trang chủ Admin</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Category")">Quản trị Danh mục</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Article")">Quản trị Bài viết</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "User")">Quản trị người dùng</a>
        </li>
    </ul>
</div>